services:
  - type: web
    name: Conceptile-assignment
    plan: free
    env: python
    region: singapore  # region should be same as your database region.
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"