# Generated by Django 5.1.4 on 2024-12-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_quizsessionquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
